### ISSUE TITLE
SCION connection issues during manual test

### ISSUE THREAD

**Issue by hyateh** [netsys-lab/scion-rains#20]
Following the instructions of the manual test for the case of SCION transport (https://github.com/netsys-lab/scion-rains/tree/master/test/manual), while publishing to an authoritative RAINS server (the error displayed is for the root zone but remains the same for any zones), the publisher fails with the following error:

> EROR[01-11|16:27:06] Error sending message to server          sever=17-ffaa:1:f44,127.0.0.1:5022 err="error receiving message: Failed to Read: Reliable socket read error\n    read unix @->/run/shm/dispatcher/default.sock: i/o timeout\n    i/o timeout"

It seems that the error is related to the underlying SCION connection. Here's my local testing environment:

- Machine: VirtualBox VM running Ubuntu 20.04 Server amd64.

- AS ID: `ffaa:1:f44`. Attachment point: `17-ffaa:0:1107`. Use OpenVPN.

- Output from `sudo systemctl list-dependencies scionlab.target` (all green, tested with sample applications):

> scionlab.target
├─scion-border-router@br-1.service
├─scion-colibri-service@co-1.service
├─scion-control-service@cs-1.service
├─scion-daemon.service
└─scion-dispatcher.service

- network interfaces:

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:22:54:18 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.4/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 585sec preferred_lft 585sec
    inet6 fe80::a00:27ff:fe22:5418/64 scope link 
       valid_lft forever preferred_lft forever
3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/none 
    inet 10.1.1.232/16 brd 10.1.255.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::5e18:d63d:f9ce:d7d7/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever

The same error occurs even when I switched a two-VM setup, where one runs the authoritative server and the other runs the publisher. The two VMs can talk with each other via `scion ping`.

**Comment by hausheer** [comment]
According to @matzf the reported error message says that the 1 second timeout waiting for a (valid) response message is hit. https://github.com/netsys-lab/scion-rains/blob/df5fe860cf73d4ddb1eaf24b4513054cebe1cfdf/internal/pkg/publisher/publisherConn.go#L29-L35
His suggestion is to start investigating whether the original message arrived at the server, and if this was processed correctly.
We shall keep in mind that also that the SCION "backend" of rains uses unreliable UDP messages and it seems that there is no retry mechanism, so these do get lost occasionally.

**Comment by benthor** [comment]
I did not find any code path in the rains server code that generated any sort of reply to a publication message. This makes this issue very closely related to #19 , which I'll close as a duplicate

**Comment by benthor** [comment]
> His suggestion is to start investigating whether the original message arrived at the server, and if this was processed correctly.
> We shall keep in mind that also that the SCION "backend" of rains uses unreliable UDP messages and it seems that there is no retry mechanism, so these do get lost occasionally.

Yes, the server receives and processes publication messages correctly. There is no indication of messages getting lost, although this can conceivably sometimes happen in case of the SCION/UDP backend.

**Comment by benthor** [comment]
Does not seem to be a blocker for the Task 1 milestone at this point

**Comment by benthor** [comment]
This has been fixed with the new architecture
