### ISSUE TITLE
Unexpected resolution behaviours

### ISSUE THREAD

**Issue by hyateh** [netsys-lab/scion-rains#21]
Several unexpected (?) behaviours observed during [manual test](https://github.com/netsys-lab/scion-rains/tree/master/test/manual):

-  return timeout (`timed out waiting for response`) when querying non-existent type (`ip4`) of existing TLD (`.ch.`), instead of authenticated negative answer or authenticated positive answer of other existing type (`redir` or `deleg`).

-  return the entire TLD zone (`ch.`) when querying non-existent SLD (`epfl.ch.`), instead of authenticated negative answer.

- return timeout (`timed out waiting for response`) when querying non-existent subdomain (`www.epfl.ch.`), instead of authenticated negative answer.

**Comment by benthor** [comment]
This has been fixed with the new architecture
